### ISSUE TITLE
How to add in a select list of values?

### ISSUE THREAD

**Issue by andrewjlow** [unboxme/PureForm#1]
This looks quite flexible and easy to use.

One thing I like to check is how do you create a list of values to select from.

Thank you!

**Comment by unboxme** [comment]
@andrewjlow, thank you for your question.

But what do you mean by that?
Maybe my few words below will be helpful.

Each cell is associated with [PFModel,](https://github.com/unboxme/PureForm/blob/master/PureForm/Models/PFModel.h) which has array of [PFInputView objects](https://github.com/unboxme/PureForm/blob/master/PureForm/Models/PFInputView.h). So it contains current value, your custom key and etc.
If you don't want to receive some pairs via `allKeyValuePairs` you just should ignore special key `<key>` in JSON file or set it to `nil` manually in PFInputView object.

Did I answer your question?
