### ISSUE TITLE
custom validator error

### ISSUE THREAD

**Issue by bayfatih2000** [unboxme/PureForm#3]
I want to add a custom validator in order to check: Minimum eight characters, at least one uppercase letter, one lowercase letter and one number. Therefore, I wrote this line in json file

"custom!": "^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)[a-zA-Z\d]{8,}$"

However, I got an error like this:

PureForm: The data couldn’t be read because it isn’t in the correct format., occurred in: +[PFJSONSerialization modelsFromFile:] [Line 49]

and my form does not appear. 

Please help me :(

**Comment by unboxme** [comment]
@bayfatih2000 Don't panic:) 
Just replace all `\` with `\\`. That's it!

**Comment by unboxme** [comment]
@bayfatih2000 And also use regex in JSON below for your checking.
`(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)[a-zA-Z\\d]{8,}$`

Hope it helps!

**Comment by bayfatih2000** [comment]
thank you very much
